/**
 * This file contains a mapping of department prefixes to icons and colors.
 * Each school is associated with a different color.
 */

import {
    IconActivityHeartbeat,
    IconAd2,
    IconAlbum,
    IconAlertTriangle,
    IconAlphabetGreek,
    IconAmbulance,
    IconAntenna,
    IconArrowsShuffle,
    IconBabyBottle,
    IconBackpack,
    IconBaguette,
    IconBarbellFilled,
    IconBellSchool,
    IconBiohazard,
    IconBodyScan,
    IconBook,
    IconBook2,
    IconBooks,
    IconBrain,
    IconBrandDeezer,
    IconBrandMessenger,
    IconBrandSpotify,
    IconBrandTwitterFilled,
    IconBriefcase,
    IconBroadcast,
    IconBrush,
    IconBubbleText,
    IconBuilding,
    IconBuildingArch,
    IconBuildingBridge,
    IconBuildingBroadcastTower,
    IconBuildingChurch,
    IconBuildingFactory2,
    IconBuildingHospital,
    IconCards,
    IconCell,
    IconChairDirector,
    IconChalkboard,
    IconChartBar,
    IconChartBubble,
    IconChecklist,
    IconCheckupList,
    IconClipboardHeart,
    IconClock,
    IconCloudLock,
    IconCode,
    IconCompass,
    IconConfucius,
    IconCpu,
    IconCrutches,
    IconCurrencyEuro,
    IconDatabase,
    IconDental,
    IconDentalBroken,
    IconDeviceAudioTape,
    IconDeviceDesktop,
    IconDeviceDesktopAnalytics,
    IconDeviceGamepad,
    IconDeviceHeartMonitor,
    IconDeviceMobile,
    IconDeviceSpeaker,
    IconDna,
    IconDna2,
    IconDumpling,
    IconEar,
    IconEarScan,
    IconEmergencyBed,
    IconExclamationCircle,
    IconEye,
    IconEyeglass,
    IconFileCheck,
    IconFileInvoice,
    IconFilters,
    IconFirstAidKit,
    IconFlask2,
    IconFlaskFilled,
    IconFriends,
    IconGasStation,
    IconGavel,
    IconGenderNeutrois,
    IconGlobe,
    IconGuitarPick,
    IconHeadphones,
    IconHeadset,
    IconHeartbeat,
    IconHeartDollar,
    IconHeartHandshake,
    IconHeartRateMonitor,
    IconHistory,
    IconHistoryToggle,
    IconHome,
    IconJewishStar,
    IconKeyframeAlignHorizontal,
    IconKeyframes,
    IconLanguage,
    IconLeaf,
    IconLibrary,
    IconLicense,
    IconLungs,
    IconMap,
    IconMap2,
    IconMasksTheater,
    IconMassage,
    IconMath,
    IconMedicalCross,
    IconMedicalCrossFilled,
    IconMedicineSyrup,
    IconMessages,
    IconMicrophone,
    IconMicrophone2,
    IconMicroscope,
    IconMoodSmile,
    IconMountain,
    IconMusic,
    IconMusicBolt,
    IconNews,
    IconNotebook,
    IconNurse,
    IconOld,
    IconPhotoScan,
    IconPhotoSearch,
    IconPiano,
    IconPill,
    IconPillFilled,
    IconPills,
    IconPizza,
    IconPlane,
    IconPlaneDeparture,
    IconPlanet,
    IconPlant2,
    IconPlaylist,
    IconPodium,
    IconPresentation,
    IconPresentationAnalytics,
    IconPuzzle,
    IconPyramid,
    IconRadio,
    IconRadioactive,
    IconRefresh,
    IconReportMedical,
    IconReportMoney,
    IconRibbonHealth,
    IconRoad,
    IconRocket,
    IconSailboat,
    IconScale,
    IconScanEye,
    IconSchool,
    IconScript,
    IconShieldHalfFilled,
    IconShovel,
    IconSlice,
    IconSlideshow,
    IconSocial,
    IconSpeakerphone,
    IconSpeedboat,
    IconStack2,
    IconStack2Filled,
    IconStereoGlasses,
    IconStretching,
    IconStretching2,
    IconSubtask,
    IconTank,
    IconTelescope,
    IconTestPipe,
    IconTie,
    IconTool,
    IconTools,
    IconTopologyStar3,
    IconTopologyStarRing,
    IconTorii,
    IconTrendingUp,
    IconUsers,
    IconUserScan,
    IconVaccine,
    IconVaccineBottle,
    IconVideo,
    IconVinyl,
    IconVirus,
    IconVirusOff,
    IconVirusSearch,
    IconVolume,
    IconWeight,
    IconWheelchair,
    IconWriting,
    IconWritingSign,
    IconZzz
} from "@tabler/icons-react"

export const courseIcons: Record<
    string,
    { Icon: React.ElementType; color: string }
> = {
    // Dornsife
    ALI: { Icon: IconLanguage, color: "green" },
    AMST: { Icon: IconPodium, color: "green" },
    ANTH: { Icon: IconFriends, color: "green" },
    ARAB: { Icon: IconLanguage, color: "green" },
    ARCG: { Icon: IconShovel, color: "green" },
    AHIS: { Icon: IconPhotoSearch, color: "green" },
    ASTR: { Icon: IconTelescope, color: "green" },
    BISC: { Icon: IconVirus, color: "green" },
    CHEM: { Icon: IconFlaskFilled, color: "green" },
    CLAS: { Icon: IconEyeglass, color: "green" },
    CGSC: { Icon: IconPuzzle, color: "green" },
    COLT: { Icon: IconBooks, color: "green" },
    CSLC: { Icon: IconBook2, color: "green" },
    EALC: { Icon: IconTorii, color: "green" },
    EASC: { Icon: IconDumpling, color: "green" },
    ECON: { Icon: IconCurrencyEuro, color: "green" },
    ENGL: { Icon: IconNotebook, color: "green" },
    ENST: { Icon: IconLeaf, color: "green" },
    FREN: { Icon: IconBaguette, color: "green" },
    FSEM: { Icon: IconPresentation, color: "green" },
    SWMS: { Icon: IconGenderNeutrois, color: "green" },
    GEOL: { Icon: IconMountain, color: "green" },
    GERM: { Icon: IconLanguage, color: "green" },
    GSEC: { Icon: IconShieldHalfFilled, color: "green" },
    GR: { Icon: IconAlphabetGreek, color: "green" },
    HEBR: { Icon: IconLanguage, color: "green" },
    HIST: { Icon: IconHistory, color: "green" },
    HBIO: { Icon: IconCell, color: "green" },
    INDS: { Icon: IconSchool, color: "green" },
    IR: { Icon: IconGlobe, color: "green" },
    ITAL: { Icon: IconPizza, color: "green" },
    JS: { Icon: IconJewishStar, color: "green" },
    LAT: { Icon: IconLanguage, color: "green" },
    LING: { Icon: IconLanguage, color: "green" },
    MATH: { Icon: IconMath, color: "green" },
    MDES: { Icon: IconPyramid, color: "green" },
    MDA: { Icon: IconSchool, color: "green" },
    NEUR: { Icon: IconBrain, color: "green" },
    NSCI: { Icon: IconBrain, color: "green" },
    OS: { Icon: IconSailboat, color: "green" },
    IRAN: { Icon: IconLanguage, color: "green" },
    PHIL: { Icon: IconConfucius, color: "green" },
    PHED: { Icon: IconBarbellFilled, color: "green" },
    PHYS: { Icon: IconWeight, color: "green" },
    POST: { Icon: IconPodium, color: "green" },
    POIR: { Icon: IconPodium, color: "green" },
    PORT: { Icon: IconLanguage, color: "green" },
    PSYC: { Icon: IconMoodSmile, color: "green" },
    QBIO: { Icon: IconTopologyStarRing, color: "green" },
    RNR: { Icon: IconSchool, color: "green" },
    REL: { Icon: IconBuildingChurch, color: "green" },
    RUSS: { Icon: IconLanguage, color: "green" },
    SLL: { Icon: IconLanguage, color: "green" },
    SOCI: { Icon: IconUsers, color: "green" },
    SPAN: { Icon: IconLanguage, color: "green" },
    SSCI: { Icon: IconMap, color: "green" },
    SMGT: { Icon: IconPlant2, color: "green" },
    SCORE: { Icon: IconWritingSign, color: "green" },
    USC: { Icon: IconSchool, color: "green" },
    VISS: { Icon: IconEye, color: "green" },
    WRIT: { Icon: IconWriting, color: "green" },
    // Leventhal
    ACCT: { Icon: IconFileInvoice, color: "#f0d99c" },
    // Architecture
    ARCH: { Icon: IconBuilding, color: "#bed4d3" },
    // Roski
    ART: { Icon: IconPhotoSearch, color: "#f79cf1" },
    CRIT: { Icon: IconChartBubble, color: "#f79cf1" },
    DES: { Icon: IconFilters, color: "#f79cf1" },
    FDN: { Icon: IconTie, color: "#f79cf1" },
    // Art, tech, and the biz of innovation
    ACAD: { Icon: IconStack2, color: "#43b591" },
    IDSN: { Icon: IconStack2Filled, color: "#43b591" },
    // Bovard
    CJ: { Icon: IconGavel, color: "#c76150" },
    EM: { Icon: IconExclamationCircle, color: "#c76150" },
    HT: { Icon: IconPlane, color: "#c76150" },
    HRM: { Icon: IconBriefcase, color: "#c76150" },
    LIM: { Icon: IconLibrary, color: "#c76150" },
    PJMT: { Icon: IconChecklist, color: "#c76150" },
    // Marshall
    BUAD: { Icon: IconTie, color: "#e69d0b" },
    BUCO: { Icon: IconPresentationAnalytics, color: "#e69d0b" },
    BAEP: { Icon: IconTrendingUp, color: "#e69d0b" },
    DSO: { Icon: IconDatabase, color: "#e69d0b" },
    FBE: { Icon: IconReportMoney, color: "#e69d0b" },
    GSBA: { Icon: IconTie, color: "#e69d0b" },
    MOR: { Icon: IconSubtask, color: "#e69d0b" },
    MKT: { Icon: IconAd2, color: "#e69d0b" },
    RISK: { Icon: IconAlertTriangle, color: "#e69d0b" },
    // Cinematic Arts
    CTAN: { Icon: IconKeyframes, color: "pink" },
    CTCS: { Icon: IconStereoGlasses, color: "pink" },
    CNTV: { Icon: IconVideo, color: "pink" },
    CTXA: { Icon: IconKeyframeAlignHorizontal, color: "pink" },
    CTIN: { Icon: IconCards, color: "pink" },
    IML: { Icon: IconDeviceGamepad, color: "pink" },
    CMPP: { Icon: IconSpeakerphone, color: "pink" },
    CTPR: { Icon: IconChairDirector, color: "pink" },
    CTWR: { Icon: IconScript, color: "pink" },
    // Annenberg
    COMM: { Icon: IconAntenna, color: "#800000" },
    ASCJ: { Icon: IconBroadcast, color: "#800000" },
    CMGT: { Icon: IconBuildingBroadcastTower, color: "#800000" },
    DMM: { Icon: IconBubbleText, color: "#800000" },
    DSM: { Icon: IconDeviceMobile, color: "#800000" },
    JOUR: { Icon: IconNews, color: "#800000" },
    PUBD: { Icon: IconHeartHandshake, color: "#800000" },
    PR: { Icon: IconBrandMessenger, color: "#800000" },
    PRSM: { Icon: IconBrandTwitterFilled, color: "#800000" },
    // Kaufman
    DANC: { Icon: IconStretching, color: "purple" },
    // Dentistry
    ADNT: { Icon: IconDental, color: "#00a8c9" },
    BMDD: { Icon: IconUserScan, color: "#00a8c9" },
    BITE: { Icon: IconCell, color: "#00a8c9" },
    COH: { Icon: IconMedicalCross, color: "#00a8c9" },
    CBY: { Icon: IconBuildingHospital, color: "#00a8c9" },
    DPBL: { Icon: IconNurse, color: "#00a8c9" },
    DENT: { Icon: IconDental, color: "#00a8c9" },
    DHIS: { Icon: IconHistoryToggle, color: "#00a8c9" },
    DPHR: { Icon: IconDental, color: "#00a8c9" },
    GPR: { Icon: IconBuildingHospital, color: "#00a8c9" },
    GDEN: { Icon: IconDentalBroken, color: "#00a8c9" },
    OPER: { Icon: IconReportMedical, color: "#00a8c9" },
    OPR: { Icon: IconRadioactive, color: "#00a8c9" },
    SURG: { Icon: IconSlice, color: "#00a8c9" },
    OFP: { Icon: IconVaccineBottle, color: "#00a8c9" },
    OFPM: { Icon: IconPills, color: "#00a8c9" },
    ORTH: { Icon: IconDentalBroken, color: "#00a8c9" },
    PEDO: { Icon: IconBabyBottle, color: "#00a8c9" },
    REST: { Icon: IconDental, color: "#00a8c9" },
    // Dramatic Arts
    THTR: { Icon: IconMasksTheater, color: "#ffe659" },
    // Rossier School of Education
    EDUC: { Icon: IconBellSchool, color: "orange" },
    EDCO: { Icon: IconMessages, color: "orange" },
    EDUE: { Icon: IconBackpack, color: "orange" },
    EDPT: { Icon: IconChalkboard, color: "orange" },
    EDHP: { Icon: IconSchool, color: "orange" },
    // Viterbi
    AME: { Icon: IconPlaneDeparture, color: "red" },
    ASTE: { Icon: IconRocket, color: "red" },
    BME: { Icon: IconHeartRateMonitor, color: "red" },
    CHE: { Icon: IconFlask2, color: "red" },
    CE: { Icon: IconBuildingBridge, color: "red" },
    CSCI: { Icon: IconCode, color: "red" },
    DSCI: { Icon: IconDeviceDesktopAnalytics, color: "red" },
    EE: { Icon: IconCpu, color: "red" },
    ENGR: { Icon: IconTools, color: "red" },
    EIS: { Icon: IconTool, color: "red" },
    ENE: { Icon: IconPhotoScan, color: "red" },
    ISE: { Icon: IconBuildingFactory2, color: "red" },
    ITP: { Icon: IconCloudLock, color: "red" },
    MASC: { Icon: IconTopologyStar3, color: "red" },
    PTE: { Icon: IconGasStation, color: "red" },
    SAE: { Icon: IconBuildingArch, color: "red" },
    // GE Requirements
    ARTS: { Icon: IconBrush, color: "#8a3c00" },
    HINQ: { Icon: IconLicense, color: "#8a3c00" },
    SANA: { Icon: IconSocial, color: "#8a3c00" },
    LIFE: { Icon: IconLungs, color: "#8a3c00" },
    PSC: { Icon: IconTestPipe, color: "#8a3c00" },
    QREA: { Icon: IconChartBar, color: "#8a3c00" },
    GPG: { Icon: IconScale, color: "#8a3c00" },
    GPH: { Icon: IconClock, color: "#8a3c00" },
    DCL: { Icon: IconBook, color: "#8a3c00" },
    GESM: { Icon: IconSlideshow, color: "#8a3c00" },
    // Gerontology
    GERO: { Icon: IconOld, color: "#76d100" },
    // Graduate Studies
    GRSC: { Icon: IconSchool, color: "black" },
    // Law
    LAW: { Icon: IconGavel, color: "black" },
    // Keck
    ACMD: { Icon: IconMedicineSyrup, color: "white" },
    ADSC: { Icon: IconVaccine, color: "white" },
    ANST: { Icon: IconZzz, color: "white" },
    BIOC: { Icon: IconMicroscope, color: "white" },
    CBG: { Icon: IconDna, color: "white" },
    DSR: { Icon: IconRefresh, color: "white" },
    HP: { Icon: IconVirusOff, color: "white" },
    IAS: { Icon: IconBodyScan, color: "white" },
    INTD: { Icon: IconMedicalCrossFilled, color: "white" },
    MEDB: { Icon: IconMicroscope, color: "white" },
    MBPH: { Icon: IconEmergencyBed, color: "white" },
    MDED: { Icon: IconHeartRateMonitor, color: "white" },
    MPHY: { Icon: IconEarScan, color: "white" },
    MEDS: { Icon: IconHeartbeat, color: "white" },
    MED: { Icon: IconFirstAidKit, color: "white" },
    MICB: { Icon: IconVirusSearch, color: "white" },
    NIIN: { Icon: IconScanEye, color: "white" },
    NEUM: { Icon: IconBrain, color: "white" },
    OHNS: { Icon: IconSlice, color: "white" },
    PAIN: { Icon: IconPillFilled, color: "white" },
    PATH: { Icon: IconActivityHeartbeat, color: "white" },
    PHBI: { Icon: IconWheelchair, color: "white" },
    PM: { Icon: IconRibbonHealth, color: "white" },
    PCPA: { Icon: IconNurse, color: "white" },
    PBHS: { Icon: IconCrutches, color: "white" },
    SCRM: { Icon: IconCell, color: "white" },
    TRGN: { Icon: IconDna2, color: "white" },
    // Thorton
    ARTL: { Icon: IconHeadset, color: "#ffc180" },
    MUCM: { Icon: IconMicrophone2, color: "#ffc180" },
    MUCO: { Icon: IconVolume, color: "#ffc180" },
    MUCD: { Icon: IconEar, color: "#ffc180" },
    MUJZ: { Icon: IconMusic, color: "#ffc180" },
    MUSC: { Icon: IconMicrophone, color: "#ffc180" },
    MUEN: { Icon: IconVinyl, color: "#ffc180" },
    MUHL: { Icon: IconVinyl, color: "#ffc180" },
    MUIN: { Icon: IconBrandSpotify, color: "#ffc180" },
    MTAL: { Icon: IconAlbum, color: "#ffc180" },
    MTEC: { Icon: IconBrandDeezer, color: "#ffc180" },
    MPEM: { Icon: IconDeviceAudioTape, color: "#ffc180" },
    MPGU: { Icon: IconGuitarPick, color: "#ffc180" },
    MPKS: { Icon: IconPiano, color: "#ffc180" },
    MPPM: { Icon: IconRadio, color: "#ffc180" },
    MPST: { Icon: IconMusicBolt, color: "#ffc180" },
    MPVA: { Icon: IconMicrophone2, color: "#ffc180" },
    MPWP: { Icon: IconDeviceSpeaker, color: "#ffc180" },
    MSCR: { Icon: IconPlaylist, color: "#ffc180" },
    SCOR: { Icon: IconHeadphones, color: "#ffc180" },
    // Nursing
    NURS: { Icon: IconNurse, color: "#ff61df" },
    // Occupational Therapy
    OT: { Icon: IconMassage, color: "#d2b48c" },
    // Pharmacy
    BPMK: { Icon: IconHeartRateMonitor, color: "#690040" },
    BPSI: { Icon: IconDeviceHeartMonitor, color: "#690040" },
    CXPT: { Icon: IconCheckupList, color: "#690040" },
    HCDA: { Icon: IconClipboardHeart, color: "#690040" },
    MPTX: { Icon: IconBiohazard, color: "#690040" },
    RXRS: { Icon: IconReportMedical, color: "#690040" },
    PMEP: { Icon: IconHeartDollar, color: "#690040" },
    PSCI: { Icon: IconPills, color: "#690040" },
    PHRD: { Icon: IconPill, color: "#690040" },
    RSCI: { Icon: IconFileCheck, color: "#690040" },
    // Physical Therapy
    BKN: { Icon: IconStretching2, color: "#460299" },
    PT: { Icon: IconStretching, color: "#460299" },
    // Price
    AEST: { Icon: IconPlanet, color: "#036300" },
    HMGT: { Icon: IconAmbulance, color: "#036300" },
    MS: { Icon: IconTank, color: "#036300" },
    NAUT: { Icon: IconCompass, color: "#036300" },
    NSC: { Icon: IconSpeedboat, color: "#036300" },
    PPD: { Icon: IconRoad, color: "#036300" },
    PPDE: { Icon: IconRoad, color: "#036300" },
    RED: { Icon: IconHome, color: "#036300" },
    PLUS: { Icon: IconMap2, color: "#036300" },
    // Social Work
    SWKC: { Icon: IconArrowsShuffle, color: "#ff7f00" },
    SWKO: { Icon: IconDeviceDesktop, color: "#ff7f00" }
}
